/* Copyright © 2014 Apex Software. All rights reserved. */
namespace Apex.Steering
{
    /// <summary>
    /// Represents the different ways height sampling can be performed
    /// </summary>
    public enum HeightSamplingMode
    {
        /// <summary>
        /// No height sampling, i.e. no height differences.
        /// </summary>
        NoHeightSampling,

        /// <summary>
        /// Use the height map generated by each grid.
        /// </summary>
        HeightMap,

        /// <summary>
        /// Use ray casting, no height map data is stored.
        /// </summary>
        Raycast
    }
}
